app/sistemavotacao/urls.py
from django.urls import include, path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views as sistemavotacao

app_name = 'sistemavotacao'

urlpatterns = [
	path('', sistemavotacao.Index.as_view(), name='home'),
	path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('cadastro/', sistemavotacao.CriarUsuario.as_view(), name='cadastro'),
	path('adicionar-proposta/', sistemavotacao.AddProposta.as_view(), name='adicionar-proposta'),
	path('proposta/detalhes/<pk>', sistemavotacao.DetalhesProposta.as_view(), name='detalhes-proposta'),
]

votacao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.sistemavotacao.urls'), name='sistemavotacao')
]

app/sistemavotacao/models.py
from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import AbstractUser, Group, Permission
import uuid

class UUIDUser(AbstractUser):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    groups = models.ManyToManyField(Group, blank=True, related_name="uuiduser_set", related_query_name="user")
    user_permissions = models.ManyToManyField(Permission, blank=True, related_name="uuiduser_set", related_query_name="user")

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'usuário'
        verbose_name_plural = 'usuários'

class Proposta(models.Model):
	ususario = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, verbose_name='usuario', related_name='users')
	nome = models.CharField(max_length = 255, verbose_name = 'nome')
	descricao = models.TextField(verbose_name = 'descrição') 
	criado = models.DateTimeField(auto_now_add = True, verbose_name = 'criação')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'proposta'
		verbose_name_plural = 'propostas'

class Comentario(models.Model):
	usuario = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, related_name='user', verbose_name='usuário')
	proposta = models.ForeignKey(Proposta, on_delete=models.CASCADE, related_name='propostas', verbose_name='proposta')
	comentario = models.TextField(verbose_name='comentário')

	def __str__(self):
		return self.comentario

	class Meta:
		verbose_name = 'comentário'
		verbose_name_plural = 'comentários'

app/sistemavotacao/forms.py
from django import forms

from . import models

class Cadastrar(forms.ModelForm):

	class Meta:
		model = models.Proposta
		fields = ('ususario', 'nome', 'descricao')
		labels = {
			'ususario': 'Usuário',
    		'nome': 'Nome',
    		'descricao': 'Descrição',
    	}

class AdicionarUsuario(forms.ModelForm):
  
  class Meta:
    model = models.UUIDUser
    fields = ('first_name', 'last_name', 'username', 'email', 'password')
    labels = {
    	'first_name': 'Primeiro Nome',
    	'last_name': 'Sobrenome',
    	'username': 'Nome de Usuário',
    	'email': 'E-mail',
    	'password': 'Senha',
    }
    widgets = {
      'password': forms.PasswordInput()
    }

app/sistemavotacao/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy

from .models import *
from .forms import *

class Index(ListView):
	model = Proposta
	template_name = 'index.html'

class DetalhesProposta(DetailView):
	model = Proposta
	template_name = 'proposta.html'

class CriarUsuario(CreateView):
    model = UUIDUser
    template_name = 'cadastrar.html'
    success_url = reverse_lazy('sistemavotacao:home')
    form_class = AdicionarUsuario

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.set_password(obj.password)
    	obj.save()
    	return super(CriarUsuario, self).form_valid(form)

class AddProposta(CreateView):
	model = Proposta
	template_name = 'adicionar.html'
	success_url = reverse_lazy('sistemavotacao:home')
	form_class = Cadastrar

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.save()
		return super(AddProposta, self).form_valid(form)



templates/adicionar.html
<!DOCTYPE html>
<html>
<head>
	<title>Adicionar Proposta</title>
</head>
<body>
	<form method="post" action="">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="enviar" value="Enviar">
	</form>
</body>
</html>

templates/cadastrar.html
<!DOCTYPE html>
<html>
<head>
	<title>Cadastrar Usuário</title>
</head>
<body>
	<form method="post">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="enviar" value="Enviar">
	</form>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Sistema de Votação</title>
</head>
<body>
<h1>Sistema de Votação</h1>
{% if request.user.is_authenticated %}
<h4>{{request.user.first_name}}</h4>
<a href="{% url 'sistemavotacao:logout' %}">Sair</a>
<a href="{% url 'sistemavotacao:adicionar-proposta' %}">Adicionar Proposta</a>
{% else %}
<a href="{% url 'sistemavotacao:login' %}">Login</a>
<a href="{% url 'sistemavotacao:cadastro' %}">Cadastro</a>
{% endif %}
{% for x in object_list %}
	<ul>
		<li>{{x.nome}}</li>
		<li>{{x.descricao}}</li>
	</ul>
{% endfor %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Cadastrar Usuário</title>
</head>
<body>
	<form method="post" action="">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="enviar" value="Enviar">
	</form>
</body>
</html>

templates/proposta.html
<!DOCTYPE html>
<html>
<head>
	<title>Detalhes da Proposta</title>
</head>
<body>
<h1>{{object.nome}}</h1>
<p>{{object.descricao}}</p>
<p>Por {{object.user.first_name}} em {{object.criado}}</p>
</body>
</html>